SELECT * FROM MEMBER;
SELECT * FROM PROJECTS;
SELECT * FROM PROJECTS_DETAILS;
SELECT * FROM PROJECTS_REWARDS;
SELECT * FROM PROJECTS_QNA;
SELECT * FROM PROJECT_FUNDING;
SELECT * FROM PROJECTS_FAVORITE;
SELECT * FROM MEM_REPORT;
SELECT * FROM MEM_BALANCE;
SELECT * FROM ADMIN;
SELECT * FROM BOARD_QNA;
SELECT * FROM BOARD_NOTICE;
SELECT * FROM BOARD_GUIDE_QNA;

SELECT * FROM (
	SELECT PRO_MAIN_IMAGE "대표이미지", PRO_TITLE "프로젝트제목", PRO_GET_FUND "현재모금액",
			trunc(PRO_GET_FUND/PRO_TARGET_FUND, 2)*100||'%' "달성률",
			trunc(PRO_FINISH_DATE-sysdate) "남은날짜"
	FROM PROJECTS p
	WHERE CATE_NAME = '가전'
	ORDER BY PRO_START_DATE)
WHERE ROWNUM <= 4;


SELECT PRO_MAIN_IMAGE "대표이미지", PRO_TITLE "프로젝트제목", PRO_GET_FUND "현재모금액",
		trunc(PRO_GET_FUND/PRO_TARGET_FUND, 2)*100||'%' "달성률",
		trunc(PRO_FINISH_DATE-sysdate) "남은날짜", PRO_HITS "조회수"
FROM PROJECTS p
WHERE 	CATE_NAME = 'IT'
		AND PRO_START_DATE <= sysdate 
		AND sysdate <= PRO_FINISH_DATE
ORDER BY PRO_START_DATE DESC;



SELECT PRO_MAIN_IMAGE "대표이미지", PRO_TITLE "프로젝트제목", PRO_GET_FUND "현재모금액",
		trunc(PRO_GET_FUND/PRO_TARGET_FUND, 2)*100||'%' "달성률",
		trunc(PRO_FINISH_DATE-sysdate) "남은날짜", PRO_HITS "조회수"
FROM PROJECTS p
WHERE 	CATE_NAME = '가전'
		AND PRO_START_DATE <= sysdate 
		AND sysdate <= PRO_FINISH_DATE
ORDER BY PRO_HITS;







SELECT PRO_MAIN_IMAGE , PRO_TITLE, PRO_GET_FUND,
		trunc(PRO_GET_FUND/PRO_TARGET_FUND, 2)*100||'%' "달성률",
		trunc(PRO_FINISH_DATE-sysdate) "남은날짜"
FROM PROJECTS p 
WHERE 	CATE_NAME = '가전'
		AND PRO_START_DATE <= sysdate 
		AND sysdate <= PRO_FINISH_DATE
ORDER BY PRO_HITS;
 

INSERT INTO PROJECTS_QNA
VALUES (projects_qna_seq01.nextval,
		1100000,
		'ezenht',
		'이 프로젝트 핵 유망주인듯, 기존 제품들 다 찌바를듯',
		'');
		
SELECT * FROM PROJECTS_QNA;