SELECT * FROM MEMBER;
SELECT * FROM PROJECTS;
SELECT * FROM PROJECTS_DETAILS;
SELECT * FROM PROJECTS_REWARDS;
SELECT * FROM PROJECTS_QNA;
SELECT * FROM PROJECT_FUNDING;
SELECT * FROM PROJECTS_FAVORITE;
SELECT * FROM MEM_REPORT;
SELECT * FROM MEM_BALANCE;
SELECT * FROM ADMIN;
SELECT * FROM BOARD_QNA;
SELECT * FROM BOARD_NOTICE;
SELECT * FROM BOARD_GUIDE_QNA;









 

INSERT INTO PROJECTS_QNA
VALUES (projects_qna_seq01.nextval,
		1100000,
		'ezenht',
		'이 프로젝트 핵 유망주인듯, 기존 제품들 다 찌바를듯',
		'');
		
SELECT * FROM PROJECTS_QNA;